"""Add service_tokens table for webhook authentication and job management

Revision ID: d5d07efcb1a7
Revises: 4df435c19dc7
Create Date: 2025-09-18 18:09:47.177063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d07efcb1a7'
down_revision: Union[str, None] = '4df435c19dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('chat_url', sa.String(), nullable=True),
    sa.Column('upload_url', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tokens_active'), 'service_tokens', ['active'], unique=False)
    op.create_index(op.f('ix_service_tokens_id'), 'service_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_service_tokens_service_name'), 'service_tokens', ['service_name'], unique=False)
    op.create_index(op.f('ix_service_tokens_token_hash'), 'service_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_tokens_token_hash'), table_name='service_tokens')
    op.drop_index(op.f('ix_service_tokens_service_name'), table_name='service_tokens')
    op.drop_index(op.f('ix_service_tokens_id'), table_name='service_tokens')
    op.drop_index(op.f('ix_service_tokens_active'), table_name='service_tokens')
    op.drop_table('service_tokens')
    # ### end Alembic commands ###
