"""Add access_token, chat_url, upload_url to service_tokens table

Revision ID: c50ae9cc73b0
Revises: f11621b33ac5
Create Date: 2025-09-18 17:30:18.902009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50ae9cc73b0'
down_revision: Union[str, None] = 'f11621b33ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tokens', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('service_tokens', sa.Column('chat_url', sa.String(), nullable=True))
    op.add_column('service_tokens', sa.Column('upload_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_tokens', 'upload_url')
    op.drop_column('service_tokens', 'chat_url')
    op.drop_column('service_tokens', 'access_token')
    # ### end Alembic commands ###
