name: Build & Test
on:
  push:
    branches:
      - main
      - develop
      - feature*
  pull_request:
    branches:
      - main
      - develop
      - feature*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          ./ci/build.sh
